### ISSUE TITLE
Crash on no res

### ISSUE THREAD

**Issue by tanaydin** [fvdm/nodejs-piwik#13]
I'm hammering this with ab, piwik works on a small machine. Sometimes mysql goes offline, and piwik goes too. So no response returns without error and it crashes like this

/Users/xxxxx/Documents/workspace/xxxxx/node_modules/piwik/piwik.js:162
        data = res.body;
                  ^
TypeError: Cannot read property 'body' of undefined

I added a control to if there is a res or not.

    if (res) {
        try {
            data = JSON.parse (res.body);
            if (data.result && data.result === 'error') {
              error = new Error ('api error');
              error.text = data.message || null;
            }
          }
          catch (e) {
            data = res.body;
          }
  
          if (res.statusCode >= 300) {
            error = new Error ('http error');
            error.code = res.statusCode;
            error.body = data;
          }
      }

so it stopped crashing.

**Comment by fvdm** [comment]
Thanks!
