### ISSUE TITLE
v1 requires trailing slash on URL - previous versions didn't

### ISSUE THREAD

**Issue by STRML** [fvdm/nodejs-piwik#14]
This creates unnecessary incompatibility between the versions.

Solution would be to test the baseURL for a trailing slash and add one if not present. It is surprising that `httpreq` doesn't do this already.

**Comment by fvdm** [comment]
Hi, in branch Issue_14 the `baseURL` is cleaned before storing, does this fix the problem?

`npm install fvdm/nodejs-piwik#Issue_14`

**Comment by STRML** [comment]
That seems like it would work. You could probably sidestep most of the issue by using a better-tested request library like [superagent](https://github.com/visionmedia/superagent) which automatically does the right thing in this particular case.

**Comment by fvdm** [comment]
Do you mean a trailing slash directly after the domain or for paths too?

Adding a slash is not always correct behavior, i.e. `http://example.net/stuff` can be a valid request.

Re superagent, I don't want a lib with dependencies for simple http. And Superagent installs 1.7MB vs httpreq 124KB.

**Comment by STRML** [comment]
Understood re: dep size. Although superagent is a common dep and can often be reused.

The issue is that superagent, request, etc., are usually smart enough not do so something like `'https://domain.com:443' + 'piwik.php' = 'https://domain.com:443piwik.php`, which `httpreq` unfortunately does.

I think the regex solution you have is good enough.

**Comment by fvdm** [comment]
Okay, submitted a [PR](https://github.com/SamDecrock/node-httpreq/pull/12) to httpreq :wink:

**Comment by SamDecrock** [comment]
@STRML a path with a trailing slash is a completely different path than one without a trailing slash.

eg 

```
http://www.google.com/index.html/
```

 is not the same as 

```
http://www.google.com/index.html
```

;-)

@fvdm Thank you for defending my library :-)

**Comment by STRML** [comment]
@SamDecrock I am well aware of that, but `'https://domain.com:443' + 'piwik.php' = 'https://domain.com:443piwik.php'` is clearly not desired behavior.

**Comment by SamDecrock** [comment]
That's why there's https://nodejs.org/api/path.html#path_path_join_path1_path2

**Comment by STRML** [comment]
Yes, I agree. Please reread the context of the ticket. I am not sure who you are trying to educate.

**Comment by SamDecrock** [comment]
Not sure either :-)

All I know is that my library (httpreq) takes in full URLs, so no base URLs. And that these full URLs should not automatically have a trailing slash appended like you're suggesting.

**Comment by STRML** [comment]
Wasn't suggesting that. Maybe @fvdm was suggesting that, but it looks like was talking about prepending a slash?

**Comment by SamDecrock** [comment]
Ok, sorry,

We'll see how the "pull request" discussion between me and @fvdm will turn out :-)

**Comment by fvdm** [comment]
It turns out `httpreq` does auto _prefix_ paths with a `/` because node's URL parser takes care of that. My PR is therefor redundant. I had no access to my dev box, so I just assumed the problem was indeed in `httpreq`. :wink: Sorry for the confusion, @SamDecrock 

My recent edit (regex) in `piwik` makes sure the path is set correctly for Piwik specifics.

**Comment by fvdm** [comment]
OK version 1.0.3 is published on npm :wink:
