### ISSUE TITLE
Cannot resolve module 'fs' in ...httpreq/lib

### ISSUE THREAD

**Issue by boxcee** [fvdm/nodejs-piwik#18]
Adding

`var piwik = require('piwik');`

makes webpack go:

ERROR in ./~/piwik/~/httpreq/lib/httpreq.js
Module not found: Error: Cannot resolve module 'fs' in /home/user/workspace/project/node_modules/piwik/node_modules/httpreq/lib
 @ ./~/piwik/~/httpreq/lib/httpreq.js 31:9-22 187:18-31

Any idea why?

**Comment by fvdm** [comment]
I don't know, fs is a core module in Node. Does webpack support Node.js?
